#!/bin/bash
#
# ESP8266 Provisioning Helper Script
#
# This script helps you:
# 1. Register a new device with AWS IoT
# 2. Extract certificates
# 3. Generate certificates.h file for Arduino
#
# Usage: ./scripts/provision-esp8266.sh <sensor-id> <location> <user-id>
#
# Example:
#   ./scripts/provision-esp8266.sh bathroom-main "Main Bathroom" user-123-456

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Configuration
AWS_REGION="us-east-2"
FUNCTION_NAME="SpottyPottySense-DeviceRegistration-dev"
OUTPUT_DIR="hardware/esp8266-sensor"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║          ESP8266 Device Provisioning Helper                   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check arguments
if [ $# -lt 3 ]; then
    echo -e "${RED}Error: Missing arguments${NC}"
    echo ""
    echo "Usage: $0 <sensor-id> <location> <user-id>"
    echo ""
    echo "Example:"
    echo "  $0 bathroom-main \"Main Bathroom\" user-123-456"
    echo ""
    exit 1
fi

SENSOR_ID="$1"
LOCATION="$2"
USER_ID="$3"

echo -e "${YELLOW}Configuration:${NC}"
echo "  Sensor ID: $SENSOR_ID"
echo "  Location: $LOCATION"
echo "  User ID: $USER_ID"
echo "  Region: $AWS_REGION"
echo ""

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo -e "${RED}✗ AWS CLI not found. Please install it first.${NC}"
    exit 1
fi

# Check jq
if ! command -v jq &> /dev/null; then
    echo -e "${RED}✗ jq not found. Please install it: brew install jq${NC}"
    exit 1
fi

# Step 1: Register device
echo -e "${BLUE}[Step 1/5] Registering device with AWS IoT...${NC}"

PAYLOAD=$(cat <<EOF
{
  "action": "register",
  "sensorId": "$SENSOR_ID",
  "location": "$LOCATION",
  "userId": "$USER_ID"
}
EOF
)

aws lambda invoke \
  --function-name "$FUNCTION_NAME" \
  --region "$AWS_REGION" \
  --cli-binary-format raw-in-base64-out \
  --payload "$PAYLOAD" \
  response-provision.json > /dev/null

# Check response
STATUS=$(cat response-provision.json | jq -r '.statusCode')

if [ "$STATUS" != "200" ]; then
    echo -e "${RED}✗ Registration failed!${NC}"
    cat response-provision.json | jq '.'
    exit 1
fi

echo -e "${GREEN}✓ Device registered successfully${NC}"

# Step 2: Extract certificates
echo -e "${BLUE}[Step 2/5] Extracting certificates...${NC}"

cat response-provision.json | jq -r '.certificatePem' > "$OUTPUT_DIR/device-cert.pem"
cat response-provision.json | jq -r '.privateKey' > "$OUTPUT_DIR/private-key.pem"
IOT_ENDPOINT=$(cat response-provision.json | jq -r '.iotEndpoint')
THING_NAME=$(cat response-provision.json | jq -r '.thingName')

echo -e "${GREEN}✓ Certificates extracted${NC}"
echo "  - device-cert.pem"
echo "  - private-key.pem"

# Step 3: Download Root CA (if not exists)
echo -e "${BLUE}[Step 3/5] Checking Root CA...${NC}"

if [ ! -f "$OUTPUT_DIR/root-ca.pem" ]; then
    curl -s https://www.amazontrust.com/repository/AmazonRootCA1.pem -o "$OUTPUT_DIR/root-ca.pem"
    echo -e "${GREEN}✓ Root CA downloaded${NC}"
else
    echo -e "${GREEN}✓ Root CA already exists${NC}"
fi

# Step 4: Generate certificates.h
echo -e "${BLUE}[Step 4/5] Generating certificates.h...${NC}"

cat > "$OUTPUT_DIR/certificates.h" << 'HEADER_START'
/**
 * AWS IoT Core Certificates
 * 
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: provision-esp8266.sh
 * 
 * This file contains your device's certificates and private key.
 * NEVER commit this file to version control!
 */

#ifndef CERTIFICATES_H
#define CERTIFICATES_H

// ============================================================================
// AMAZON ROOT CA 1
// ============================================================================

const char AWS_ROOT_CA[] PROGMEM = R"EOF(
HEADER_START

cat "$OUTPUT_DIR/root-ca.pem" >> "$OUTPUT_DIR/certificates.h"

cat >> "$OUTPUT_DIR/certificates.h" << 'MIDDLE_PART'
)EOF";

// ============================================================================
// DEVICE CERTIFICATE
// ============================================================================

const char AWS_DEVICE_CERT[] PROGMEM = R"EOF(
MIDDLE_PART

cat "$OUTPUT_DIR/device-cert.pem" >> "$OUTPUT_DIR/certificates.h"

cat >> "$OUTPUT_DIR/certificates.h" << 'MIDDLE_PART2'
)EOF";

// ============================================================================
// PRIVATE KEY
// ============================================================================

const char AWS_PRIVATE_KEY[] PROGMEM = R"EOF(
MIDDLE_PART2

cat "$OUTPUT_DIR/private-key.pem" >> "$OUTPUT_DIR/certificates.h"

cat >> "$OUTPUT_DIR/certificates.h" << 'FOOTER'
)EOF";

#endif // CERTIFICATES_H
FOOTER

echo -e "${GREEN}✓ certificates.h generated${NC}"

# Step 5: Create config summary
echo -e "${BLUE}[Step 5/5] Creating configuration summary...${NC}"

cat > "$OUTPUT_DIR/PROVISIONING_INFO.txt" << EOF
╔════════════════════════════════════════════════════════════════╗
║         Device Provisioning Complete!                         ║
╚════════════════════════════════════════════════════════════════╝

Device Information:
───────────────────────────────────────────────────────────────
Sensor ID:      $SENSOR_ID
Location:       $LOCATION
User ID:        $USER_ID
Thing Name:     $THING_NAME
IoT Endpoint:   $IOT_ENDPOINT

Files Generated:
───────────────────────────────────────────────────────────────
✓ device-cert.pem       - Device certificate
✓ private-key.pem       - Private key
✓ root-ca.pem           - Amazon Root CA
✓ certificates.h        - Arduino header file

Next Steps:
───────────────────────────────────────────────────────────────
1. Update config.h with these values:

   #define WIFI_SSID "YourWiFiSSID"
   #define WIFI_PASSWORD "YourWiFiPassword"
   #define AWS_IOT_ENDPOINT "$IOT_ENDPOINT"
   #define SENSOR_ID "$SENSOR_ID"

2. Open Arduino IDE:
   File → Open → hardware/esp8266-sensor/esp8266-sensor.ino

3. Upload firmware:
   Tools → Board → NodeMCU 1.0
   Tools → Port → Select your port
   Sketch → Upload

4. Open Serial Monitor (115200 baud) to verify

Security Reminder:
───────────────────────────────────────────────────────────────
⚠️  NEVER commit certificates.h to git
⚠️  Keep private-key.pem secure
⚠️  Certificates are added to .gitignore automatically

Provisioned at: $(date)
EOF

cat "$OUTPUT_DIR/PROVISIONING_INFO.txt"

# Cleanup response file
rm -f response-provision.json

# Clean up PEM files (they're in certificates.h now)
echo ""
echo -e "${YELLOW}Cleaning up PEM files (already in certificates.h)...${NC}"
rm -f "$OUTPUT_DIR/device-cert.pem"
rm -f "$OUTPUT_DIR/private-key.pem"
echo -e "${GREEN}✓ PEM files removed (certificates.h contains everything)${NC}"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Provisioning Complete!                           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Next: Edit config.h and upload firmware to ESP8266${NC}"
echo -e "${BLUE}Guide: hardware/docs/SETUP.md${NC}"
echo ""
